-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: Entity.proto


module Entity exposing (..)

import Protobuf exposing (..)
import Json.Decode as JD
import Json.Encode as JE


type alias Group =
    { id :
        Int
        -- 1
    , name :
        String
        -- 2
    , slug :
        String
        -- 3
    , created :
        Maybe Timestamp
        -- 4
    , updated :
        Maybe Timestamp
        -- 5
    }


groupDecoder : JD.Decoder Group
groupDecoder =
    JD.lazy <|
        \_ ->
            decode Group
                |> required "id" JD.int 0
                |> required "name" JD.string ""
                |> required "slug" JD.string ""
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


groupEncoder : Group -> JE.Value
groupEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias GroupRecord =
    { name :
        String
        -- 1
    , slug :
        String
        -- 2
    }


groupRecordDecoder : JD.Decoder GroupRecord
groupRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GroupRecord
                |> required "name" JD.string ""
                |> required "slug" JD.string ""


groupRecordEncoder : GroupRecord -> JE.Value
groupRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            ]


type alias GroupRequest =
    { groupSlug :
        String
        -- 1
    }


groupRequestDecoder : JD.Decoder GroupRequest
groupRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GroupRequest
                |> required "groupSlug" JD.string ""


groupRequestEncoder : GroupRequest -> JE.Value
groupRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "groupSlug" JE.string "" v.groupSlug)
            ]


type alias Role =
    { id :
        Int
        -- 1
    , name :
        String
        -- 2
    , weight :
        Int
        -- 3
    }


roleDecoder : JD.Decoder Role
roleDecoder =
    JD.lazy <|
        \_ ->
            decode Role
                |> required "id" JD.int 0
                |> required "name" JD.string ""
                |> required "weight" JD.int 0


roleEncoder : Role -> JE.Value
roleEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "weight" JE.int 0 v.weight)
            ]


type alias RoleRequest =
    { roleName :
        String
        -- 1
    }


roleRequestDecoder : JD.Decoder RoleRequest
roleRequestDecoder =
    JD.lazy <|
        \_ ->
            decode RoleRequest
                |> required "roleName" JD.string ""


roleRequestEncoder : RoleRequest -> JE.Value
roleRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "roleName" JE.string "" v.roleName)
            ]


type alias User =
    { id :
        Int
        -- 1
    , username :
        String
        -- 2
    , email :
        String
        -- 3
    , firstName :
        String
        -- 4
    , lastName :
        String
        -- 5
    , avatar :
        String
        -- 6
    , groupID :
        Int
        -- 7
    , roles :
        List Role
        -- 8
    , lastLogin :
        Maybe Timestamp
        -- 9
    , blocked :
        Maybe Timestamp
        -- 10
    , created :
        Maybe Timestamp
        -- 11
    , updated :
        Maybe Timestamp
        -- 12
    , deleted :
        Maybe Timestamp
        -- 13
    }


userDecoder : JD.Decoder User
userDecoder =
    JD.lazy <|
        \_ ->
            decode User
                |> required "id" JD.int 0
                |> required "username" JD.string ""
                |> required "email" JD.string ""
                |> required "firstName" JD.string ""
                |> required "lastName" JD.string ""
                |> required "avatar" JD.string ""
                |> required "groupID" JD.int 0
                |> repeated "roles" roleDecoder
                |> optional "lastLogin" timestampDecoder
                |> optional "blocked" timestampDecoder
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder
                |> optional "deleted" timestampDecoder


userEncoder : User -> JE.Value
userEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "username" JE.string "" v.username)
            , (requiredFieldEncoder "email" JE.string "" v.email)
            , (requiredFieldEncoder "firstName" JE.string "" v.firstName)
            , (requiredFieldEncoder "lastName" JE.string "" v.lastName)
            , (requiredFieldEncoder "avatar" JE.string "" v.avatar)
            , (requiredFieldEncoder "groupID" JE.int 0 v.groupID)
            , (repeatedFieldEncoder "roles" roleEncoder v.roles)
            , (optionalEncoder "lastLogin" timestampEncoder v.lastLogin)
            , (optionalEncoder "blocked" timestampEncoder v.blocked)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            , (optionalEncoder "deleted" timestampEncoder v.deleted)
            ]


type alias UserRecord =
    { username :
        String
        -- 1
    , email :
        String
        -- 2
    , firstName :
        String
        -- 3
    , lastName :
        String
        -- 4
    , avatar :
        String
        -- 5
    , groupID :
        Int
        -- 6
    , roles :
        List Int
        -- 7
    , password :
        String
        -- 8
    }


userRecordDecoder : JD.Decoder UserRecord
userRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserRecord
                |> required "username" JD.string ""
                |> required "email" JD.string ""
                |> required "firstName" JD.string ""
                |> required "lastName" JD.string ""
                |> required "avatar" JD.string ""
                |> required "groupID" JD.int 0
                |> repeated "roles" JD.int
                |> required "password" JD.string ""


userRecordEncoder : UserRecord -> JE.Value
userRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "username" JE.string "" v.username)
            , (requiredFieldEncoder "email" JE.string "" v.email)
            , (requiredFieldEncoder "firstName" JE.string "" v.firstName)
            , (requiredFieldEncoder "lastName" JE.string "" v.lastName)
            , (requiredFieldEncoder "avatar" JE.string "" v.avatar)
            , (requiredFieldEncoder "groupID" JE.int 0 v.groupID)
            , (repeatedFieldEncoder "roles" JE.int v.roles)
            , (requiredFieldEncoder "password" JE.string "" v.password)
            ]


type alias UserRequest =
    { userId :
        Int
        -- 1
    }


userRequestDecoder : JD.Decoder UserRequest
userRequestDecoder =
    JD.lazy <|
        \_ ->
            decode UserRequest
                |> required "userId" JD.int 0


userRequestEncoder : UserRequest -> JE.Value
userRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.int 0 v.userId)
            ]


type alias UserPassResetRecord =
    { userEmail :
        String
        -- 1
    , proof :
        String
        -- 2
    }


userPassResetRecordDecoder : JD.Decoder UserPassResetRecord
userPassResetRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserPassResetRecord
                |> required "userEmail" JD.string ""
                |> required "proof" JD.string ""


userPassResetRecordEncoder : UserPassResetRecord -> JE.Value
userPassResetRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userEmail" JE.string "" v.userEmail)
            , (requiredFieldEncoder "proof" JE.string "" v.proof)
            ]


type alias Users =
    { users :
        List User
        -- 1
    }


usersDecoder : JD.Decoder Users
usersDecoder =
    JD.lazy <|
        \_ ->
            decode Users
                |> repeated "users" userDecoder


usersEncoder : Users -> JE.Value
usersEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "users" userEncoder v.users)
            ]


type alias UsersRecord =
    { records :
        List UserRecord
        -- 1
    }


usersRecordDecoder : JD.Decoder UsersRecord
usersRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UsersRecord
                |> repeated "records" userRecordDecoder


usersRecordEncoder : UsersRecord -> JE.Value
usersRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "records" userRecordEncoder v.records)
            ]


type alias UsersRequest =
    { userIds :
        List Int
        -- 1
    }


usersRequestDecoder : JD.Decoder UsersRequest
usersRequestDecoder =
    JD.lazy <|
        \_ ->
            decode UsersRequest
                |> repeated "userIds" JD.int


usersRequestEncoder : UsersRequest -> JE.Value
usersRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "userIds" JE.int v.userIds)
            ]


type alias UsersReferral =
    { idFirst :
        Int
        -- 1
    , idFinal :
        Int
        -- 2
    , idDesc :
        Bool
        -- 3
    , limit :
        Int
        -- 4
    , skip :
        Int
        -- 5
    }


usersReferralDecoder : JD.Decoder UsersReferral
usersReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UsersReferral
                |> required "idFirst" JD.int 0
                |> required "idFinal" JD.int 0
                |> required "idDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


usersReferralEncoder : UsersReferral -> JE.Value
usersReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "idFirst" JE.int 0 v.idFirst)
            , (requiredFieldEncoder "idFinal" JE.int 0 v.idFinal)
            , (requiredFieldEncoder "idDesc" JE.bool False v.idDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]


type alias Auth =
    { token :
        String
        -- 1
    }


authDecoder : JD.Decoder Auth
authDecoder =
    JD.lazy <|
        \_ ->
            decode Auth
                |> required "token" JD.string ""


authEncoder : Auth -> JE.Value
authEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "token" JE.string "" v.token)
            ]


type alias AuthRecord =
    { email :
        String
        -- 1
    , password :
        String
        -- 2
    }


authRecordDecoder : JD.Decoder AuthRecord
authRecordDecoder =
    JD.lazy <|
        \_ ->
            decode AuthRecord
                |> required "email" JD.string ""
                |> required "password" JD.string ""


authRecordEncoder : AuthRecord -> JE.Value
authRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "email" JE.string "" v.email)
            , (requiredFieldEncoder "password" JE.string "" v.password)
            ]


type alias AuthRedactor =
    { authToken :
        String
        -- 1
    }


authRedactorDecoder : JD.Decoder AuthRedactor
authRedactorDecoder =
    JD.lazy <|
        \_ ->
            decode AuthRedactor
                |> required "authToken" JD.string ""


authRedactorEncoder : AuthRedactor -> JE.Value
authRedactorEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "authToken" JE.string "" v.authToken)
            ]


type alias Game =
    { id :
        Int
        -- 1
    , name :
        String
        -- 2
    , slug :
        String
        -- 3
    , dscript :
        String
        -- 4
    , icon :
        String
        -- 5
    , reactDur :
        Int
        -- 6
    , sessDur :
        Int
        -- 7
    , trialDur :
        Int
        -- 8
    , offsetDur :
        Int
        -- 9
    , fixDur :
        Int
        -- 10
    , fixImg :
        String
        -- 11
    , durInc :
        Int
        -- 12
    , durDec :
        Int
        -- 13
    , incTrigger :
        Int
        -- 14
    , decTrigger :
        Int
        -- 15
    , blocked :
        Maybe Timestamp
        -- 16
    , created :
        Maybe Timestamp
        -- 17
    , updated :
        Maybe Timestamp
        -- 18
    , deleted :
        Maybe Timestamp
        -- 19
    }


gameDecoder : JD.Decoder Game
gameDecoder =
    JD.lazy <|
        \_ ->
            decode Game
                |> required "id" JD.int 0
                |> required "name" JD.string ""
                |> required "slug" JD.string ""
                |> required "dscript" JD.string ""
                |> required "icon" JD.string ""
                |> required "reactDur" JD.int 0
                |> required "sessDur" JD.int 0
                |> required "trialDur" JD.int 0
                |> required "offsetDur" JD.int 0
                |> required "fixDur" JD.int 0
                |> required "fixImg" JD.string ""
                |> required "durInc" JD.int 0
                |> required "durDec" JD.int 0
                |> required "incTrigger" JD.int 0
                |> required "decTrigger" JD.int 0
                |> optional "blocked" timestampDecoder
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder
                |> optional "deleted" timestampDecoder


gameEncoder : Game -> JE.Value
gameEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            , (requiredFieldEncoder "dscript" JE.string "" v.dscript)
            , (requiredFieldEncoder "icon" JE.string "" v.icon)
            , (requiredFieldEncoder "reactDur" JE.int 0 v.reactDur)
            , (requiredFieldEncoder "sessDur" JE.int 0 v.sessDur)
            , (requiredFieldEncoder "trialDur" JE.int 0 v.trialDur)
            , (requiredFieldEncoder "offsetDur" JE.int 0 v.offsetDur)
            , (requiredFieldEncoder "fixDur" JE.int 0 v.fixDur)
            , (requiredFieldEncoder "fixImg" JE.string "" v.fixImg)
            , (requiredFieldEncoder "durInc" JE.int 0 v.durInc)
            , (requiredFieldEncoder "durDec" JE.int 0 v.durDec)
            , (requiredFieldEncoder "incTrigger" JE.int 0 v.incTrigger)
            , (requiredFieldEncoder "decTrigger" JE.int 0 v.decTrigger)
            , (optionalEncoder "blocked" timestampEncoder v.blocked)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            , (optionalEncoder "deleted" timestampEncoder v.deleted)
            ]


type alias GameRequest =
    { gameSlug :
        String
        -- 1
    }


gameRequestDecoder : JD.Decoder GameRequest
gameRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GameRequest
                |> required "gameSlug" JD.string ""


gameRequestEncoder : GameRequest -> JE.Value
gameRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gameSlug" JE.string "" v.gameSlug)
            ]


type alias Gameplay =
    { id :
        Int
        -- 1
    , gameId :
        Int
        -- 2
    , duration :
        Int
        -- 3
    , created :
        Maybe Timestamp
        -- 4
    , updated :
        Maybe Timestamp
        -- 5
    }


gameplayDecoder : JD.Decoder Gameplay
gameplayDecoder =
    JD.lazy <|
        \_ ->
            decode Gameplay
                |> required "id" JD.int 0
                |> required "gameId" JD.int 0
                |> required "duration" JD.int 0
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


gameplayEncoder : Gameplay -> JE.Value
gameplayEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "gameId" JE.int 0 v.gameId)
            , (requiredFieldEncoder "duration" JE.int 0 v.duration)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias Gameplays =
    { gameplays :
        List Gameplay
        -- 1
    }


gameplaysDecoder : JD.Decoder Gameplays
gameplaysDecoder =
    JD.lazy <|
        \_ ->
            decode Gameplays
                |> repeated "gameplays" gameplayDecoder


gameplaysEncoder : Gameplays -> JE.Value
gameplaysEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "gameplays" gameplayEncoder v.gameplays)
            ]


type alias UserGameplaysReferral =
    { userId :
        Int
        -- 1
    , gameIds :
        List Int
        -- 2
    }


userGameplaysReferralDecoder : JD.Decoder UserGameplaysReferral
userGameplaysReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UserGameplaysReferral
                |> required "userId" JD.int 0
                |> repeated "gameIds" JD.int


userGameplaysReferralEncoder : UserGameplaysReferral -> JE.Value
userGameplaysReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.int 0 v.userId)
            , (repeatedFieldEncoder "gameIds" JE.int v.gameIds)
            ]


type alias Gimgtype =
    { id :
        Int
        -- 1
    , slug :
        String
        -- 2
    }


gimgtypeDecoder : JD.Decoder Gimgtype
gimgtypeDecoder =
    JD.lazy <|
        \_ ->
            decode Gimgtype
                |> required "id" JD.int 0
                |> required "slug" JD.string ""


gimgtypeEncoder : Gimgtype -> JE.Value
gimgtypeEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            ]


type alias Gimgtypes =
    { gimgtypes :
        List Gimgtype
        -- 1
    }


gimgtypesDecoder : JD.Decoder Gimgtypes
gimgtypesDecoder =
    JD.lazy <|
        \_ ->
            decode Gimgtypes
                |> repeated "gimgtypes" gimgtypeDecoder


gimgtypesEncoder : Gimgtypes -> JE.Value
gimgtypesEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "gimgtypes" gimgtypeEncoder v.gimgtypes)
            ]


type alias GimgtypesRequest =
    { gimgtypeIds :
        List Int
        -- 1
    }


gimgtypesRequestDecoder : JD.Decoder GimgtypesRequest
gimgtypesRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GimgtypesRequest
                |> repeated "gimgtypeIds" JD.int


gimgtypesRequestEncoder : GimgtypesRequest -> JE.Value
gimgtypesRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "gimgtypeIds" JE.int v.gimgtypeIds)
            ]


type alias Gimage =
    { id :
        Int
        -- 1
    , name :
        String
        -- 2
    , path :
        String
        -- 3
    , gimgtypeId :
        Int
        -- 4
    , created :
        Maybe Timestamp
        -- 5
    , updated :
        Maybe Timestamp
        -- 6
    , deleted :
        Maybe Timestamp
        -- 7
    }


gimageDecoder : JD.Decoder Gimage
gimageDecoder =
    JD.lazy <|
        \_ ->
            decode Gimage
                |> required "id" JD.int 0
                |> required "name" JD.string ""
                |> required "path" JD.string ""
                |> required "gimgtypeId" JD.int 0
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder
                |> optional "deleted" timestampDecoder


gimageEncoder : Gimage -> JE.Value
gimageEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "path" JE.string "" v.path)
            , (requiredFieldEncoder "gimgtypeId" JE.int 0 v.gimgtypeId)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            , (optionalEncoder "deleted" timestampEncoder v.deleted)
            ]


type alias GimageRecord =
    { name :
        String
        -- 1
    , path :
        String
        -- 2
    , gimgtypeId :
        Int
        -- 3
    }


gimageRecordDecoder : JD.Decoder GimageRecord
gimageRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GimageRecord
                |> required "name" JD.string ""
                |> required "path" JD.string ""
                |> required "gimgtypeId" JD.int 0


gimageRecordEncoder : GimageRecord -> JE.Value
gimageRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "path" JE.string "" v.path)
            , (requiredFieldEncoder "gimgtypeId" JE.int 0 v.gimgtypeId)
            ]


type alias Ugimgset =
    { id :
        Int
        -- 1
    , ref :
        String
        -- 2
    , userId :
        Int
        -- 3
    , created :
        Maybe Timestamp
        -- 4
    , updated :
        Maybe Timestamp
        -- 5
    }


ugimgsetDecoder : JD.Decoder Ugimgset
ugimgsetDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimgset
                |> required "id" JD.int 0
                |> required "ref" JD.string ""
                |> required "userId" JD.int 0
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


ugimgsetEncoder : Ugimgset -> JE.Value
ugimgsetEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (requiredFieldEncoder "ref" JE.string "" v.ref)
            , (requiredFieldEncoder "userId" JE.int 0 v.userId)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias Ugimgsets =
    { ugimgsets :
        List Ugimgset
        -- 1
    }


ugimgsetsDecoder : JD.Decoder Ugimgsets
ugimgsetsDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimgsets
                |> repeated "ugimgsets" ugimgsetDecoder


ugimgsetsEncoder : Ugimgsets -> JE.Value
ugimgsetsEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "ugimgsets" ugimgsetEncoder v.ugimgsets)
            ]


type alias UserUgimgsetRecord =
    { userId :
        Int
        -- 1
    , ref :
        String
        -- 2
    }


userUgimgsetRecordDecoder : JD.Decoder UserUgimgsetRecord
userUgimgsetRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserUgimgsetRecord
                |> required "userId" JD.int 0
                |> required "ref" JD.string ""


userUgimgsetRecordEncoder : UserUgimgsetRecord -> JE.Value
userUgimgsetRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.int 0 v.userId)
            , (requiredFieldEncoder "ref" JE.string "" v.ref)
            ]


type alias UserUgimgsetRequest =
    { userId :
        Int
        -- 1
    , ugimgsetRef :
        String
        -- 2
    }


userUgimgsetRequestDecoder : JD.Decoder UserUgimgsetRequest
userUgimgsetRequestDecoder =
    JD.lazy <|
        \_ ->
            decode UserUgimgsetRequest
                |> required "userId" JD.int 0
                |> required "ugimgsetRef" JD.string ""


userUgimgsetRequestEncoder : UserUgimgsetRequest -> JE.Value
userUgimgsetRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.int 0 v.userId)
            , (requiredFieldEncoder "ugimgsetRef" JE.string "" v.ugimgsetRef)
            ]


type alias UserUgimgsetsReferral =
    { userId :
        Int
        -- 1
    , createdFirst :
        Maybe Timestamp
        -- 2
    , createdFinal :
        Maybe Timestamp
        -- 3
    , createdDesc :
        Bool
        -- 4
    , limit :
        Int
        -- 5
    , skip :
        Int
        -- 6
    }


userUgimgsetsReferralDecoder : JD.Decoder UserUgimgsetsReferral
userUgimgsetsReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UserUgimgsetsReferral
                |> required "userId" JD.int 0
                |> optional "createdFirst" timestampDecoder
                |> optional "createdFinal" timestampDecoder
                |> required "createdDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


userUgimgsetsReferralEncoder : UserUgimgsetsReferral -> JE.Value
userUgimgsetsReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.int 0 v.userId)
            , (optionalEncoder "createdFirst" timestampEncoder v.createdFirst)
            , (optionalEncoder "createdFinal" timestampEncoder v.createdFinal)
            , (requiredFieldEncoder "createdDesc" JE.bool False v.createdDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]


type alias Ugimage =
    { id :
        Int
        -- 1
    , gimage :
        Maybe Gimage
        -- 2
    , ugimgsetId :
        Int
        -- 3
    , val :
        Int
        -- 4
    }


ugimageDecoder : JD.Decoder Ugimage
ugimageDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimage
                |> required "id" JD.int 0
                |> optional "gimage" gimageDecoder
                |> required "ugimgsetId" JD.int 0
                |> required "val" JD.int 0


ugimageEncoder : Ugimage -> JE.Value
ugimageEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.int 0 v.id)
            , (optionalEncoder "gimage" gimageEncoder v.gimage)
            , (requiredFieldEncoder "ugimgsetId" JE.int 0 v.ugimgsetId)
            , (requiredFieldEncoder "val" JE.int 0 v.val)
            ]


type alias Ugimages =
    { ugimages :
        List Ugimage
        -- 1
    }


ugimagesDecoder : JD.Decoder Ugimages
ugimagesDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimages
                |> repeated "ugimages" ugimageDecoder


ugimagesEncoder : Ugimages -> JE.Value
ugimagesEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "ugimages" ugimageEncoder v.ugimages)
            ]


type alias UgimgsetUgimageRecord =
    { gimageName :
        String
        -- 1
    , ugimgsetId :
        Int
        -- 2
    , val :
        Int
        -- 3
    }


ugimgsetUgimageRecordDecoder : JD.Decoder UgimgsetUgimageRecord
ugimgsetUgimageRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UgimgsetUgimageRecord
                |> required "gimageName" JD.string ""
                |> required "ugimgsetId" JD.int 0
                |> required "val" JD.int 0


ugimgsetUgimageRecordEncoder : UgimgsetUgimageRecord -> JE.Value
ugimgsetUgimageRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gimageName" JE.string "" v.gimageName)
            , (requiredFieldEncoder "ugimgsetId" JE.int 0 v.ugimgsetId)
            , (requiredFieldEncoder "val" JE.int 0 v.val)
            ]


type alias UgimgsetUgimagesReferral =
    { ugimgsetId :
        Int
        -- 1
    , gimgtypeSlug :
        String
        -- 2
    , valFirst :
        Int
        -- 3
    , valFinal :
        Int
        -- 4
    , valDesc :
        Bool
        -- 5
    , limit :
        Int
        -- 6
    , skip :
        Int
        -- 7
    }


ugimgsetUgimagesReferralDecoder : JD.Decoder UgimgsetUgimagesReferral
ugimgsetUgimagesReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UgimgsetUgimagesReferral
                |> required "ugimgsetId" JD.int 0
                |> required "gimgtypeSlug" JD.string ""
                |> required "valFirst" JD.int 0
                |> required "valFinal" JD.int 0
                |> required "valDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


ugimgsetUgimagesReferralEncoder : UgimgsetUgimagesReferral -> JE.Value
ugimgsetUgimagesReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "ugimgsetId" JE.int 0 v.ugimgsetId)
            , (requiredFieldEncoder "gimgtypeSlug" JE.string "" v.gimgtypeSlug)
            , (requiredFieldEncoder "valFirst" JE.int 0 v.valFirst)
            , (requiredFieldEncoder "valFinal" JE.int 0 v.valFinal)
            , (requiredFieldEncoder "valDesc" JE.bool False v.valDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]
