-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: Entity.proto


module Entity exposing (..)

import Protobuf exposing (..)
import Json.Decode as JD
import Json.Encode as JE


type alias Group =
    { id :
        String
        -- 1
    , name :
        String
        -- 2
    , slug :
        String
        -- 3
    , created :
        Maybe Timestamp
        -- 4
    , updated :
        Maybe Timestamp
        -- 5
    }


groupDecoder : JD.Decoder Group
groupDecoder =
    JD.lazy <|
        \_ ->
            decode Group
                |> required "id" JD.string ""
                |> required "name" JD.string ""
                |> required "slug" JD.string ""
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


groupEncoder : Group -> JE.Value
groupEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias GroupRecord =
    { name :
        String
        -- 1
    , slug :
        String
        -- 2
    }


groupRecordDecoder : JD.Decoder GroupRecord
groupRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GroupRecord
                |> required "name" JD.string ""
                |> required "slug" JD.string ""


groupRecordEncoder : GroupRecord -> JE.Value
groupRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            ]


type alias GroupRequest =
    { groupSlug :
        String
        -- 1
    }


groupRequestDecoder : JD.Decoder GroupRequest
groupRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GroupRequest
                |> required "groupSlug" JD.string ""


groupRequestEncoder : GroupRequest -> JE.Value
groupRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "groupSlug" JE.string "" v.groupSlug)
            ]


type alias Role =
    { id :
        String
        -- 1
    , name :
        String
        -- 2
    , weight :
        Int
        -- 3
    }


roleDecoder : JD.Decoder Role
roleDecoder =
    JD.lazy <|
        \_ ->
            decode Role
                |> required "id" JD.string ""
                |> required "name" JD.string ""
                |> required "weight" JD.int 0


roleEncoder : Role -> JE.Value
roleEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "weight" JE.int 0 v.weight)
            ]


type alias RoleRequest =
    { roleName :
        String
        -- 1
    }


roleRequestDecoder : JD.Decoder RoleRequest
roleRequestDecoder =
    JD.lazy <|
        \_ ->
            decode RoleRequest
                |> required "roleName" JD.string ""


roleRequestEncoder : RoleRequest -> JE.Value
roleRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "roleName" JE.string "" v.roleName)
            ]


type alias User =
    { id :
        String
        -- 1
    , username :
        String
        -- 2
    , email :
        String
        -- 3
    , firstName :
        String
        -- 4
    , lastName :
        String
        -- 5
    , avatar :
        String
        -- 6
    , groupId :
        String
        -- 7
    , roles :
        List Role
        -- 8
    , lastLogin :
        Maybe Timestamp
        -- 9
    , blocked :
        Maybe Timestamp
        -- 10
    , created :
        Maybe Timestamp
        -- 11
    , updated :
        Maybe Timestamp
        -- 12
    , deleted :
        Maybe Timestamp
        -- 13
    }


userDecoder : JD.Decoder User
userDecoder =
    JD.lazy <|
        \_ ->
            decode User
                |> required "id" JD.string ""
                |> required "username" JD.string ""
                |> required "email" JD.string ""
                |> required "firstName" JD.string ""
                |> required "lastName" JD.string ""
                |> required "avatar" JD.string ""
                |> required "groupId" JD.string ""
                |> repeated "roles" roleDecoder
                |> optional "lastLogin" timestampDecoder
                |> optional "blocked" timestampDecoder
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder
                |> optional "deleted" timestampDecoder


userEncoder : User -> JE.Value
userEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "username" JE.string "" v.username)
            , (requiredFieldEncoder "email" JE.string "" v.email)
            , (requiredFieldEncoder "firstName" JE.string "" v.firstName)
            , (requiredFieldEncoder "lastName" JE.string "" v.lastName)
            , (requiredFieldEncoder "avatar" JE.string "" v.avatar)
            , (requiredFieldEncoder "groupId" JE.string "" v.groupId)
            , (repeatedFieldEncoder "roles" roleEncoder v.roles)
            , (optionalEncoder "lastLogin" timestampEncoder v.lastLogin)
            , (optionalEncoder "blocked" timestampEncoder v.blocked)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            , (optionalEncoder "deleted" timestampEncoder v.deleted)
            ]


type alias UserRecord =
    { username :
        String
        -- 1
    , email :
        String
        -- 2
    , firstName :
        String
        -- 3
    , lastName :
        String
        -- 4
    , avatar :
        String
        -- 5
    , groupId :
        String
        -- 6
    , roles :
        List String
        -- 7
    , password :
        String
        -- 8
    }


userRecordDecoder : JD.Decoder UserRecord
userRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserRecord
                |> required "username" JD.string ""
                |> required "email" JD.string ""
                |> required "firstName" JD.string ""
                |> required "lastName" JD.string ""
                |> required "avatar" JD.string ""
                |> required "groupId" JD.string ""
                |> repeated "roles" JD.string
                |> required "password" JD.string ""


userRecordEncoder : UserRecord -> JE.Value
userRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "username" JE.string "" v.username)
            , (requiredFieldEncoder "email" JE.string "" v.email)
            , (requiredFieldEncoder "firstName" JE.string "" v.firstName)
            , (requiredFieldEncoder "lastName" JE.string "" v.lastName)
            , (requiredFieldEncoder "avatar" JE.string "" v.avatar)
            , (requiredFieldEncoder "groupId" JE.string "" v.groupId)
            , (repeatedFieldEncoder "roles" JE.string v.roles)
            , (requiredFieldEncoder "password" JE.string "" v.password)
            ]


type alias UserRecorder =
    { userId :
        String
        -- 1
    , userRecord :
        Maybe UserRecord
        -- 2
    }


userRecorderDecoder : JD.Decoder UserRecorder
userRecorderDecoder =
    JD.lazy <|
        \_ ->
            decode UserRecorder
                |> required "userId" JD.string ""
                |> optional "userRecord" userRecordDecoder


userRecorderEncoder : UserRecorder -> JE.Value
userRecorderEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (optionalEncoder "userRecord" userRecordEncoder v.userRecord)
            ]


type alias UserRequest =
    { userId :
        String
        -- 1
    }


userRequestDecoder : JD.Decoder UserRequest
userRequestDecoder =
    JD.lazy <|
        \_ ->
            decode UserRequest
                |> required "userId" JD.string ""


userRequestEncoder : UserRequest -> JE.Value
userRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            ]


type alias UserPassResetRecord =
    { userEmail :
        String
        -- 1
    , proof :
        String
        -- 2
    }


userPassResetRecordDecoder : JD.Decoder UserPassResetRecord
userPassResetRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserPassResetRecord
                |> required "userEmail" JD.string ""
                |> required "proof" JD.string ""


userPassResetRecordEncoder : UserPassResetRecord -> JE.Value
userPassResetRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userEmail" JE.string "" v.userEmail)
            , (requiredFieldEncoder "proof" JE.string "" v.proof)
            ]


type alias Users =
    { users :
        List User
        -- 1
    }


usersDecoder : JD.Decoder Users
usersDecoder =
    JD.lazy <|
        \_ ->
            decode Users
                |> repeated "users" userDecoder


usersEncoder : Users -> JE.Value
usersEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "users" userEncoder v.users)
            ]


type alias UsersRecord =
    { records :
        List UserRecord
        -- 1
    }


usersRecordDecoder : JD.Decoder UsersRecord
usersRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UsersRecord
                |> repeated "records" userRecordDecoder


usersRecordEncoder : UsersRecord -> JE.Value
usersRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "records" userRecordEncoder v.records)
            ]


type alias UsersReferral =
    { groupId :
        String
        -- 1
    , roleId :
        String
        -- 2
    , createdFirst :
        Maybe Timestamp
        -- 3
    , createdFinal :
        Maybe Timestamp
        -- 4
    , createdEach :
        Bool
        -- 5
    , createdDesc :
        Bool
        -- 6
    , limit :
        Int
        -- 7
    , skip :
        Int
        -- 8
    }


usersReferralDecoder : JD.Decoder UsersReferral
usersReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UsersReferral
                |> required "groupId" JD.string ""
                |> required "roleId" JD.string ""
                |> optional "createdFirst" timestampDecoder
                |> optional "createdFinal" timestampDecoder
                |> required "createdEach" JD.bool False
                |> required "createdDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


usersReferralEncoder : UsersReferral -> JE.Value
usersReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "groupId" JE.string "" v.groupId)
            , (requiredFieldEncoder "roleId" JE.string "" v.roleId)
            , (optionalEncoder "createdFirst" timestampEncoder v.createdFirst)
            , (optionalEncoder "createdFinal" timestampEncoder v.createdFinal)
            , (requiredFieldEncoder "createdEach" JE.bool False v.createdEach)
            , (requiredFieldEncoder "createdDesc" JE.bool False v.createdDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]


type alias UserRedactor =
    { userId :
        String
        -- 1
    }


userRedactorDecoder : JD.Decoder UserRedactor
userRedactorDecoder =
    JD.lazy <|
        \_ ->
            decode UserRedactor
                |> required "userId" JD.string ""


userRedactorEncoder : UserRedactor -> JE.Value
userRedactorEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            ]


type alias Auth =
    { token :
        String
        -- 1
    }


authDecoder : JD.Decoder Auth
authDecoder =
    JD.lazy <|
        \_ ->
            decode Auth
                |> required "token" JD.string ""


authEncoder : Auth -> JE.Value
authEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "token" JE.string "" v.token)
            ]


type alias AuthRecord =
    { email :
        String
        -- 1
    , password :
        String
        -- 2
    }


authRecordDecoder : JD.Decoder AuthRecord
authRecordDecoder =
    JD.lazy <|
        \_ ->
            decode AuthRecord
                |> required "email" JD.string ""
                |> required "password" JD.string ""


authRecordEncoder : AuthRecord -> JE.Value
authRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "email" JE.string "" v.email)
            , (requiredFieldEncoder "password" JE.string "" v.password)
            ]


type alias AuthRedactor =
    { authToken :
        String
        -- 1
    }


authRedactorDecoder : JD.Decoder AuthRedactor
authRedactorDecoder =
    JD.lazy <|
        \_ ->
            decode AuthRedactor
                |> required "authToken" JD.string ""


authRedactorEncoder : AuthRedactor -> JE.Value
authRedactorEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "authToken" JE.string "" v.authToken)
            ]


type alias Game =
    { id :
        String
        -- 1
    , name :
        String
        -- 2
    , slug :
        String
        -- 3
    , dscript :
        String
        -- 4
    , instruct :
        String
        -- 5
    , icon :
        String
        -- 6
    , reactDur :
        Int
        -- 7
    , sessDur :
        Int
        -- 8
    , trialDur :
        Int
        -- 9
    , offsetDur :
        Int
        -- 10
    , fixDur :
        Int
        -- 11
    , fixImg :
        String
        -- 12
    , durInc :
        Int
        -- 13
    , durDec :
        Int
        -- 14
    , incTrigger :
        Int
        -- 15
    , decTrigger :
        Int
        -- 16
    , blocked :
        Maybe Timestamp
        -- 17
    , created :
        Maybe Timestamp
        -- 18
    , updated :
        Maybe Timestamp
        -- 19
    , deleted :
        Maybe Timestamp
        -- 20
    }


gameDecoder : JD.Decoder Game
gameDecoder =
    JD.lazy <|
        \_ ->
            decode Game
                |> required "id" JD.string ""
                |> required "name" JD.string ""
                |> required "slug" JD.string ""
                |> required "dscript" JD.string ""
                |> required "instruct" JD.string ""
                |> required "icon" JD.string ""
                |> required "reactDur" JD.int 0
                |> required "sessDur" JD.int 0
                |> required "trialDur" JD.int 0
                |> required "offsetDur" JD.int 0
                |> required "fixDur" JD.int 0
                |> required "fixImg" JD.string ""
                |> required "durInc" JD.int 0
                |> required "durDec" JD.int 0
                |> required "incTrigger" JD.int 0
                |> required "decTrigger" JD.int 0
                |> optional "blocked" timestampDecoder
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder
                |> optional "deleted" timestampDecoder


gameEncoder : Game -> JE.Value
gameEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            , (requiredFieldEncoder "dscript" JE.string "" v.dscript)
            , (requiredFieldEncoder "instruct" JE.string "" v.instruct)
            , (requiredFieldEncoder "icon" JE.string "" v.icon)
            , (requiredFieldEncoder "reactDur" JE.int 0 v.reactDur)
            , (requiredFieldEncoder "sessDur" JE.int 0 v.sessDur)
            , (requiredFieldEncoder "trialDur" JE.int 0 v.trialDur)
            , (requiredFieldEncoder "offsetDur" JE.int 0 v.offsetDur)
            , (requiredFieldEncoder "fixDur" JE.int 0 v.fixDur)
            , (requiredFieldEncoder "fixImg" JE.string "" v.fixImg)
            , (requiredFieldEncoder "durInc" JE.int 0 v.durInc)
            , (requiredFieldEncoder "durDec" JE.int 0 v.durDec)
            , (requiredFieldEncoder "incTrigger" JE.int 0 v.incTrigger)
            , (requiredFieldEncoder "decTrigger" JE.int 0 v.decTrigger)
            , (optionalEncoder "blocked" timestampEncoder v.blocked)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            , (optionalEncoder "deleted" timestampEncoder v.deleted)
            ]


type alias GameRequest =
    { gameSlug :
        String
        -- 1
    }


gameRequestDecoder : JD.Decoder GameRequest
gameRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GameRequest
                |> required "gameSlug" JD.string ""


gameRequestEncoder : GameRequest -> JE.Value
gameRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gameSlug" JE.string "" v.gameSlug)
            ]


type alias Ginstruct =
    { id :
        String
        -- 1
    , gameId :
        String
        -- 2
    , groupId :
        String
        -- 3
    , instruct :
        String
        -- 4
    , created :
        Maybe Timestamp
        -- 5
    , updated :
        Maybe Timestamp
        -- 6
    }


ginstructDecoder : JD.Decoder Ginstruct
ginstructDecoder =
    JD.lazy <|
        \_ ->
            decode Ginstruct
                |> required "id" JD.string ""
                |> required "gameId" JD.string ""
                |> required "groupId" JD.string ""
                |> required "instruct" JD.string ""
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


ginstructEncoder : Ginstruct -> JE.Value
ginstructEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "gameId" JE.string "" v.gameId)
            , (requiredFieldEncoder "groupId" JE.string "" v.groupId)
            , (requiredFieldEncoder "instruct" JE.string "" v.instruct)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias Ginstructs =
    { ginstructs :
        List Ginstruct
        -- 1
    }


ginstructsDecoder : JD.Decoder Ginstructs
ginstructsDecoder =
    JD.lazy <|
        \_ ->
            decode Ginstructs
                |> repeated "ginstructs" ginstructDecoder


ginstructsEncoder : Ginstructs -> JE.Value
ginstructsEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "ginstructs" ginstructEncoder v.ginstructs)
            ]


type alias GameGroupGinstructRecord =
    { gameId :
        String
        -- 1
    , groupId :
        String
        -- 2
    , instruct :
        String
        -- 3
    }


gameGroupGinstructRecordDecoder : JD.Decoder GameGroupGinstructRecord
gameGroupGinstructRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GameGroupGinstructRecord
                |> required "gameId" JD.string ""
                |> required "groupId" JD.string ""
                |> required "instruct" JD.string ""


gameGroupGinstructRecordEncoder : GameGroupGinstructRecord -> JE.Value
gameGroupGinstructRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gameId" JE.string "" v.gameId)
            , (requiredFieldEncoder "groupId" JE.string "" v.groupId)
            , (requiredFieldEncoder "instruct" JE.string "" v.instruct)
            ]


type alias GameGroupGinstructsReferral =
    { gameId :
        String
        -- 1
    , groupId :
        String
        -- 2
    }


gameGroupGinstructsReferralDecoder : JD.Decoder GameGroupGinstructsReferral
gameGroupGinstructsReferralDecoder =
    JD.lazy <|
        \_ ->
            decode GameGroupGinstructsReferral
                |> required "gameId" JD.string ""
                |> required "groupId" JD.string ""


gameGroupGinstructsReferralEncoder : GameGroupGinstructsReferral -> JE.Value
gameGroupGinstructsReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gameId" JE.string "" v.gameId)
            , (requiredFieldEncoder "groupId" JE.string "" v.groupId)
            ]


type alias Gsession =
    { id :
        String
        -- 1
    , userId :
        String
        -- 2
    , gameId :
        String
        -- 3
    , start :
        String
        -- 4
    , end :
        String
        -- 5
    , created :
        Maybe Timestamp
        -- 6
    , updated :
        Maybe Timestamp
        -- 7
    }


gsessionDecoder : JD.Decoder Gsession
gsessionDecoder =
    JD.lazy <|
        \_ ->
            decode Gsession
                |> required "id" JD.string ""
                |> required "userId" JD.string ""
                |> required "gameId" JD.string ""
                |> required "start" JD.string ""
                |> required "end" JD.string ""
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


gsessionEncoder : Gsession -> JE.Value
gsessionEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (requiredFieldEncoder "gameId" JE.string "" v.gameId)
            , (requiredFieldEncoder "start" JE.string "" v.start)
            , (requiredFieldEncoder "end" JE.string "" v.end)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias Gsessions =
    { gsessions :
        List Gsession
        -- 1
    }


gsessionsDecoder : JD.Decoder Gsessions
gsessionsDecoder =
    JD.lazy <|
        \_ ->
            decode Gsessions
                |> repeated "gsessions" gsessionDecoder


gsessionsEncoder : Gsessions -> JE.Value
gsessionsEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "gsessions" gsessionEncoder v.gsessions)
            ]


type alias GsessionsReferral =
    { userId :
        String
        -- 1
    , userEach :
        Bool
        -- 2
    , gameId :
        String
        -- 3
    , gameEach :
        Bool
        -- 4
    , hasEnd :
        Bool
        -- 5
    , hasEndEach :
        Bool
        -- 6
    , createdFirst :
        Maybe Timestamp
        -- 7
    , createdFinal :
        Maybe Timestamp
        -- 8
    , createdEach :
        Bool
        -- 9
    , createdDesc :
        Bool
        -- 10
    , limit :
        Int
        -- 11
    , skip :
        Int
        -- 12
    }


gsessionsReferralDecoder : JD.Decoder GsessionsReferral
gsessionsReferralDecoder =
    JD.lazy <|
        \_ ->
            decode GsessionsReferral
                |> required "userId" JD.string ""
                |> required "userEach" JD.bool False
                |> required "gameId" JD.string ""
                |> required "gameEach" JD.bool False
                |> required "hasEnd" JD.bool False
                |> required "hasEndEach" JD.bool False
                |> optional "createdFirst" timestampDecoder
                |> optional "createdFinal" timestampDecoder
                |> required "createdEach" JD.bool False
                |> required "createdDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


gsessionsReferralEncoder : GsessionsReferral -> JE.Value
gsessionsReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (requiredFieldEncoder "userEach" JE.bool False v.userEach)
            , (requiredFieldEncoder "gameId" JE.string "" v.gameId)
            , (requiredFieldEncoder "gameEach" JE.bool False v.gameEach)
            , (requiredFieldEncoder "hasEnd" JE.bool False v.hasEnd)
            , (requiredFieldEncoder "hasEndEach" JE.bool False v.hasEndEach)
            , (optionalEncoder "createdFirst" timestampEncoder v.createdFirst)
            , (optionalEncoder "createdFinal" timestampEncoder v.createdFinal)
            , (requiredFieldEncoder "createdEach" JE.bool False v.createdEach)
            , (requiredFieldEncoder "createdDesc" JE.bool False v.createdDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]


type alias UserGsessionRecord =
    { userId :
        String
        -- 1
    , gameId :
        String
        -- 2
    , start :
        String
        -- 3
    , end :
        String
        -- 4
    }


userGsessionRecordDecoder : JD.Decoder UserGsessionRecord
userGsessionRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserGsessionRecord
                |> required "userId" JD.string ""
                |> required "gameId" JD.string ""
                |> required "start" JD.string ""
                |> required "end" JD.string ""


userGsessionRecordEncoder : UserGsessionRecord -> JE.Value
userGsessionRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (requiredFieldEncoder "gameId" JE.string "" v.gameId)
            , (requiredFieldEncoder "start" JE.string "" v.start)
            , (requiredFieldEncoder "end" JE.string "" v.end)
            ]


type alias GsessionRecorder =
    { gsessionId :
        String
        -- 1
    , userGsessionRecord :
        Maybe UserGsessionRecord
        -- 2
    }


gsessionRecorderDecoder : JD.Decoder GsessionRecorder
gsessionRecorderDecoder =
    JD.lazy <|
        \_ ->
            decode GsessionRecorder
                |> required "gsessionId" JD.string ""
                |> optional "UserGsessionRecord" userGsessionRecordDecoder


gsessionRecorderEncoder : GsessionRecorder -> JE.Value
gsessionRecorderEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gsessionId" JE.string "" v.gsessionId)
            , (optionalEncoder "UserGsessionRecord" userGsessionRecordEncoder v.userGsessionRecord)
            ]


type alias Gcycle =
    { id :
        String
        -- 1
    , gsessionId :
        String
        -- 2
    , report :
        String
        -- 3
    , fixation :
        String
        -- 4
    , selection :
        String
        -- 5
    , instruct :
        String
        -- 6
    , jitter :
        String
        -- 7
    , pictures :
        String
        -- 8
    , filler :
        String
        -- 9
    , cross :
        String
        -- 10
    , picnobord :
        String
        -- 11
    , picbord :
        String
        -- 12
    , xCoords :
        Int
        -- 13
    , yCoords :
        Int
        -- 14
    , blue :
        Bool
        -- 15
    , reasonId :
        String
        -- 16
    }


gcycleDecoder : JD.Decoder Gcycle
gcycleDecoder =
    JD.lazy <|
        \_ ->
            decode Gcycle
                |> required "id" JD.string ""
                |> required "gsessionId" JD.string ""
                |> required "report" JD.string ""
                |> required "fixation" JD.string ""
                |> required "selection" JD.string ""
                |> required "instruct" JD.string ""
                |> required "jitter" JD.string ""
                |> required "pictures" JD.string ""
                |> required "filler" JD.string ""
                |> required "cross" JD.string ""
                |> required "picnobord" JD.string ""
                |> required "picbord" JD.string ""
                |> required "xCoords" JD.int 0
                |> required "yCoords" JD.int 0
                |> required "blue" JD.bool False
                |> required "reasonId" JD.string ""


gcycleEncoder : Gcycle -> JE.Value
gcycleEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "gsessionId" JE.string "" v.gsessionId)
            , (requiredFieldEncoder "report" JE.string "" v.report)
            , (requiredFieldEncoder "fixation" JE.string "" v.fixation)
            , (requiredFieldEncoder "selection" JE.string "" v.selection)
            , (requiredFieldEncoder "instruct" JE.string "" v.instruct)
            , (requiredFieldEncoder "jitter" JE.string "" v.jitter)
            , (requiredFieldEncoder "pictures" JE.string "" v.pictures)
            , (requiredFieldEncoder "filler" JE.string "" v.filler)
            , (requiredFieldEncoder "cross" JE.string "" v.cross)
            , (requiredFieldEncoder "picnobord" JE.string "" v.picnobord)
            , (requiredFieldEncoder "picbord" JE.string "" v.picbord)
            , (requiredFieldEncoder "xCoords" JE.int 0 v.xCoords)
            , (requiredFieldEncoder "yCoords" JE.int 0 v.yCoords)
            , (requiredFieldEncoder "blue" JE.bool False v.blue)
            , (requiredFieldEncoder "reasonId" JE.string "" v.reasonId)
            ]


type alias GsessionGcycleRecord =
    { gsessionId :
        String
        -- 1
    , report :
        String
        -- 2
    , fixation :
        String
        -- 3
    , selection :
        String
        -- 4
    , instruct :
        String
        -- 5
    , jitter :
        String
        -- 6
    , pictures :
        String
        -- 7
    , filler :
        String
        -- 8
    , cross :
        String
        -- 9
    , picnobord :
        String
        -- 10
    , picbord :
        String
        -- 11
    , xCoords :
        Int
        -- 12
    , yCoords :
        Int
        -- 13
    , blue :
        Bool
        -- 14
    , reasonId :
        String
        -- 15
    }


gsessionGcycleRecordDecoder : JD.Decoder GsessionGcycleRecord
gsessionGcycleRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GsessionGcycleRecord
                |> required "gsessionId" JD.string ""
                |> required "report" JD.string ""
                |> required "fixation" JD.string ""
                |> required "selection" JD.string ""
                |> required "instruct" JD.string ""
                |> required "jitter" JD.string ""
                |> required "pictures" JD.string ""
                |> required "filler" JD.string ""
                |> required "cross" JD.string ""
                |> required "picnobord" JD.string ""
                |> required "picbord" JD.string ""
                |> required "xCoords" JD.int 0
                |> required "yCoords" JD.int 0
                |> required "blue" JD.bool False
                |> required "reasonId" JD.string ""


gsessionGcycleRecordEncoder : GsessionGcycleRecord -> JE.Value
gsessionGcycleRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gsessionId" JE.string "" v.gsessionId)
            , (requiredFieldEncoder "report" JE.string "" v.report)
            , (requiredFieldEncoder "fixation" JE.string "" v.fixation)
            , (requiredFieldEncoder "selection" JE.string "" v.selection)
            , (requiredFieldEncoder "instruct" JE.string "" v.instruct)
            , (requiredFieldEncoder "jitter" JE.string "" v.jitter)
            , (requiredFieldEncoder "pictures" JE.string "" v.pictures)
            , (requiredFieldEncoder "filler" JE.string "" v.filler)
            , (requiredFieldEncoder "cross" JE.string "" v.cross)
            , (requiredFieldEncoder "picnobord" JE.string "" v.picnobord)
            , (requiredFieldEncoder "picbord" JE.string "" v.picbord)
            , (requiredFieldEncoder "xCoords" JE.int 0 v.xCoords)
            , (requiredFieldEncoder "yCoords" JE.int 0 v.yCoords)
            , (requiredFieldEncoder "blue" JE.bool False v.blue)
            , (requiredFieldEncoder "reasonId" JE.string "" v.reasonId)
            ]


type alias Gcycles =
    { gcycles :
        List Gcycle
        -- 1
    }


gcyclesDecoder : JD.Decoder Gcycles
gcyclesDecoder =
    JD.lazy <|
        \_ ->
            decode Gcycles
                |> repeated "gcycles" gcycleDecoder


gcyclesEncoder : Gcycles -> JE.Value
gcyclesEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "gcycles" gcycleEncoder v.gcycles)
            ]


type alias GsessionGcyclesRecord =
    { gsessionId :
        String
        -- 1
    , records :
        List GsessionGcycleRecord
        -- 2
    }


gsessionGcyclesRecordDecoder : JD.Decoder GsessionGcyclesRecord
gsessionGcyclesRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GsessionGcyclesRecord
                |> required "gsessionId" JD.string ""
                |> repeated "records" gsessionGcycleRecordDecoder


gsessionGcyclesRecordEncoder : GsessionGcyclesRecord -> JE.Value
gsessionGcyclesRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gsessionId" JE.string "" v.gsessionId)
            , (repeatedFieldEncoder "records" gsessionGcycleRecordEncoder v.records)
            ]


type alias Gimgtype =
    { id :
        String
        -- 1
    , slug :
        String
        -- 2
    }


gimgtypeDecoder : JD.Decoder Gimgtype
gimgtypeDecoder =
    JD.lazy <|
        \_ ->
            decode Gimgtype
                |> required "id" JD.string ""
                |> required "slug" JD.string ""


gimgtypeEncoder : Gimgtype -> JE.Value
gimgtypeEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "slug" JE.string "" v.slug)
            ]


type alias Gimgtypes =
    { gimgtypes :
        List Gimgtype
        -- 1
    }


gimgtypesDecoder : JD.Decoder Gimgtypes
gimgtypesDecoder =
    JD.lazy <|
        \_ ->
            decode Gimgtypes
                |> repeated "gimgtypes" gimgtypeDecoder


gimgtypesEncoder : Gimgtypes -> JE.Value
gimgtypesEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "gimgtypes" gimgtypeEncoder v.gimgtypes)
            ]


type alias GimgtypeRequest =
    { gimgtypeSlug :
        String
        -- 1
    }


gimgtypeRequestDecoder : JD.Decoder GimgtypeRequest
gimgtypeRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GimgtypeRequest
                |> required "gimgtypeSlug" JD.string ""


gimgtypeRequestEncoder : GimgtypeRequest -> JE.Value
gimgtypeRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gimgtypeSlug" JE.string "" v.gimgtypeSlug)
            ]


type alias Gimage =
    { id :
        String
        -- 1
    , name :
        String
        -- 2
    , path :
        String
        -- 3
    , gimgtypeId :
        String
        -- 4
    , created :
        Maybe Timestamp
        -- 5
    , updated :
        Maybe Timestamp
        -- 6
    , deleted :
        Maybe Timestamp
        -- 7
    }


gimageDecoder : JD.Decoder Gimage
gimageDecoder =
    JD.lazy <|
        \_ ->
            decode Gimage
                |> required "id" JD.string ""
                |> required "name" JD.string ""
                |> required "path" JD.string ""
                |> required "gimgtypeId" JD.string ""
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder
                |> optional "deleted" timestampDecoder


gimageEncoder : Gimage -> JE.Value
gimageEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "path" JE.string "" v.path)
            , (requiredFieldEncoder "gimgtypeId" JE.string "" v.gimgtypeId)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            , (optionalEncoder "deleted" timestampEncoder v.deleted)
            ]


type alias GimageRecord =
    { name :
        String
        -- 1
    , path :
        String
        -- 2
    , gimgtypeId :
        String
        -- 3
    }


gimageRecordDecoder : JD.Decoder GimageRecord
gimageRecordDecoder =
    JD.lazy <|
        \_ ->
            decode GimageRecord
                |> required "name" JD.string ""
                |> required "path" JD.string ""
                |> required "gimgtypeId" JD.string ""


gimageRecordEncoder : GimageRecord -> JE.Value
gimageRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "name" JE.string "" v.name)
            , (requiredFieldEncoder "path" JE.string "" v.path)
            , (requiredFieldEncoder "gimgtypeId" JE.string "" v.gimgtypeId)
            ]


type alias GimageRequest =
    { gimageName :
        String
        -- 1
    }


gimageRequestDecoder : JD.Decoder GimageRequest
gimageRequestDecoder =
    JD.lazy <|
        \_ ->
            decode GimageRequest
                |> required "gimageName" JD.string ""


gimageRequestEncoder : GimageRequest -> JE.Value
gimageRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gimageName" JE.string "" v.gimageName)
            ]


type alias Ugimgset =
    { id :
        String
        -- 1
    , ref :
        String
        -- 2
    , userId :
        String
        -- 3
    , created :
        Maybe Timestamp
        -- 4
    , updated :
        Maybe Timestamp
        -- 5
    }


ugimgsetDecoder : JD.Decoder Ugimgset
ugimgsetDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimgset
                |> required "id" JD.string ""
                |> required "ref" JD.string ""
                |> required "userId" JD.string ""
                |> optional "created" timestampDecoder
                |> optional "updated" timestampDecoder


ugimgsetEncoder : Ugimgset -> JE.Value
ugimgsetEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (requiredFieldEncoder "ref" JE.string "" v.ref)
            , (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (optionalEncoder "created" timestampEncoder v.created)
            , (optionalEncoder "updated" timestampEncoder v.updated)
            ]


type alias Ugimgsets =
    { ugimgsets :
        List Ugimgset
        -- 1
    }


ugimgsetsDecoder : JD.Decoder Ugimgsets
ugimgsetsDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimgsets
                |> repeated "ugimgsets" ugimgsetDecoder


ugimgsetsEncoder : Ugimgsets -> JE.Value
ugimgsetsEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "ugimgsets" ugimgsetEncoder v.ugimgsets)
            ]


type alias UserUgimgsetRecord =
    { userId :
        String
        -- 1
    , ref :
        String
        -- 2
    }


userUgimgsetRecordDecoder : JD.Decoder UserUgimgsetRecord
userUgimgsetRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UserUgimgsetRecord
                |> required "userId" JD.string ""
                |> required "ref" JD.string ""


userUgimgsetRecordEncoder : UserUgimgsetRecord -> JE.Value
userUgimgsetRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (requiredFieldEncoder "ref" JE.string "" v.ref)
            ]


type alias UserUgimgsetRequest =
    { userId :
        String
        -- 1
    , ugimgsetRef :
        String
        -- 2
    }


userUgimgsetRequestDecoder : JD.Decoder UserUgimgsetRequest
userUgimgsetRequestDecoder =
    JD.lazy <|
        \_ ->
            decode UserUgimgsetRequest
                |> required "userId" JD.string ""
                |> required "ugimgsetRef" JD.string ""


userUgimgsetRequestEncoder : UserUgimgsetRequest -> JE.Value
userUgimgsetRequestEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (requiredFieldEncoder "ugimgsetRef" JE.string "" v.ugimgsetRef)
            ]


type alias UserUgimgsetsReferral =
    { userId :
        String
        -- 1
    , createdFirst :
        Maybe Timestamp
        -- 2
    , createdFinal :
        Maybe Timestamp
        -- 3
    , createdEach :
        Bool
        -- 4
    , createdDesc :
        Bool
        -- 5
    , limit :
        Int
        -- 6
    , skip :
        Int
        -- 7
    }


userUgimgsetsReferralDecoder : JD.Decoder UserUgimgsetsReferral
userUgimgsetsReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UserUgimgsetsReferral
                |> required "userId" JD.string ""
                |> optional "createdFirst" timestampDecoder
                |> optional "createdFinal" timestampDecoder
                |> required "createdEach" JD.bool False
                |> required "createdDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


userUgimgsetsReferralEncoder : UserUgimgsetsReferral -> JE.Value
userUgimgsetsReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "userId" JE.string "" v.userId)
            , (optionalEncoder "createdFirst" timestampEncoder v.createdFirst)
            , (optionalEncoder "createdFinal" timestampEncoder v.createdFinal)
            , (requiredFieldEncoder "createdEach" JE.bool False v.createdEach)
            , (requiredFieldEncoder "createdDesc" JE.bool False v.createdDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]


type alias Ugimage =
    { id :
        String
        -- 1
    , gimage :
        Maybe Gimage
        -- 2
    , ugimgsetId :
        String
        -- 3
    , val :
        Int
        -- 4
    }


ugimageDecoder : JD.Decoder Ugimage
ugimageDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimage
                |> required "id" JD.string ""
                |> optional "gimage" gimageDecoder
                |> required "ugimgsetId" JD.string ""
                |> required "val" JD.int 0


ugimageEncoder : Ugimage -> JE.Value
ugimageEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "id" JE.string "" v.id)
            , (optionalEncoder "gimage" gimageEncoder v.gimage)
            , (requiredFieldEncoder "ugimgsetId" JE.string "" v.ugimgsetId)
            , (requiredFieldEncoder "val" JE.int 0 v.val)
            ]


type alias Ugimages =
    { ugimages :
        List Ugimage
        -- 1
    }


ugimagesDecoder : JD.Decoder Ugimages
ugimagesDecoder =
    JD.lazy <|
        \_ ->
            decode Ugimages
                |> repeated "ugimages" ugimageDecoder


ugimagesEncoder : Ugimages -> JE.Value
ugimagesEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (repeatedFieldEncoder "ugimages" ugimageEncoder v.ugimages)
            ]


type alias UgimgsetUgimageRecord =
    { gimageName :
        String
        -- 1
    , ugimgsetId :
        String
        -- 2
    , val :
        Int
        -- 3
    }


ugimgsetUgimageRecordDecoder : JD.Decoder UgimgsetUgimageRecord
ugimgsetUgimageRecordDecoder =
    JD.lazy <|
        \_ ->
            decode UgimgsetUgimageRecord
                |> required "gimageName" JD.string ""
                |> required "ugimgsetId" JD.string ""
                |> required "val" JD.int 0


ugimgsetUgimageRecordEncoder : UgimgsetUgimageRecord -> JE.Value
ugimgsetUgimageRecordEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "gimageName" JE.string "" v.gimageName)
            , (requiredFieldEncoder "ugimgsetId" JE.string "" v.ugimgsetId)
            , (requiredFieldEncoder "val" JE.int 0 v.val)
            ]


type alias UgimgsetUgimagesReferral =
    { ugimgsetId :
        String
        -- 1
    , gimgtypeSlug :
        String
        -- 2
    , valFirst :
        Int
        -- 3
    , valFinal :
        Int
        -- 4
    , valEach :
        Bool
        -- 5
    , valDesc :
        Bool
        -- 6
    , limit :
        Int
        -- 7
    , skip :
        Int
        -- 8
    }


ugimgsetUgimagesReferralDecoder : JD.Decoder UgimgsetUgimagesReferral
ugimgsetUgimagesReferralDecoder =
    JD.lazy <|
        \_ ->
            decode UgimgsetUgimagesReferral
                |> required "ugimgsetId" JD.string ""
                |> required "gimgtypeSlug" JD.string ""
                |> required "valFirst" JD.int 0
                |> required "valFinal" JD.int 0
                |> required "valEach" JD.bool False
                |> required "valDesc" JD.bool False
                |> required "limit" JD.int 0
                |> required "skip" JD.int 0


ugimgsetUgimagesReferralEncoder : UgimgsetUgimagesReferral -> JE.Value
ugimgsetUgimagesReferralEncoder v =
    JE.object <|
        List.filterMap identity <|
            [ (requiredFieldEncoder "ugimgsetId" JE.string "" v.ugimgsetId)
            , (requiredFieldEncoder "gimgtypeSlug" JE.string "" v.gimgtypeSlug)
            , (requiredFieldEncoder "valFirst" JE.int 0 v.valFirst)
            , (requiredFieldEncoder "valFinal" JE.int 0 v.valFinal)
            , (requiredFieldEncoder "valEach" JE.bool False v.valEach)
            , (requiredFieldEncoder "valDesc" JE.bool False v.valDesc)
            , (requiredFieldEncoder "limit" JE.int 0 v.limit)
            , (requiredFieldEncoder "skip" JE.int 0 v.skip)
            ]
